package com.ousman.controller;

import com.ousman.model.Payment;
import com.ousman.service.PaymentService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.Map;

/**
 * ─────────────────────────────────────────────────────────────────────────
 *  Payment Controller — Role-Based Access
 *
 *  Payments are never created directly here — they're generated by
 *  SaleService whenever a sale is recorded or a loan repayment is posted.
 *  This controller only reads them and lets ADMIN correct/delete a record.
 *
 *  ADMIN:  GET (page/by-code), PUT (edit notes/ref), DELETE
 *  WORKER: GET only
 * ─────────────────────────────────────────────────────────────────────────
 */
@RestController
@RequestMapping("/api/payments")
public class PaymentController {

    @Autowired
    private PaymentService paymentService;

    // Friendly sort keys the frontend sends → real JPA property paths.
    private static final Map<String, String> SORT_FIELDS = Map.of(
        "date",     "paymentDate",
        "amount",   "amountPaid",
        "customer", "customerName",
        "method",   "paymentMethod",
        "cashier",  "cashier",
        "bank",     "bank.name"
    );

    // GET /api/payments/page — paginated, searchable, filterable, sortable
    @GetMapping("/page")
    @PreAuthorize("hasAnyRole('ADMIN', 'WORKER', 'WAREHOUSE_MANAGER', 'STORE_MANAGER', 'STAFF')")
    public ResponseEntity<Page<Payment>> getPage(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "20") int size,
            @RequestParam(required = false) String search,
            @RequestParam(required = false) String method,
            @RequestParam(required = false) Long bankId,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate from,
            @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate to,
            @RequestParam(defaultValue = "date") String sortBy,
            @RequestParam(defaultValue = "desc") String sortDir) {

        String field = SORT_FIELDS.getOrDefault(sortBy, "paymentDate");
        Sort.Direction dir = "asc".equalsIgnoreCase(sortDir) ? Sort.Direction.ASC : Sort.Direction.DESC;
        Sort sort = "paymentDate".equals(field)
                ? Sort.by(dir, "paymentDate").and(Sort.by(dir, "paymentTime"))
                : Sort.by(dir, field);

        Pageable pageable = PageRequest.of(page, size, sort);
        return ResponseEntity.ok(paymentService.search(search, method, bankId, from, to, pageable));
    }

    // GET /api/payments/{code} — lookup by human-facing payment code, e.g. PAY-000123
    @GetMapping("/{code}")
    @PreAuthorize("hasAnyRole('ADMIN', 'WORKER', 'WAREHOUSE_MANAGER', 'STORE_MANAGER', 'STAFF')")
    public ResponseEntity<?> getByCode(@PathVariable String code) {
        try {
            return ResponseEntity.ok(paymentService.getByCode(code));
        } catch (RuntimeException e) {
            return ResponseEntity.notFound().build();
        }
    }

    // PUT /api/payments/{code} — ADMIN only: correct transactionRef / notes
    @PutMapping("/{code}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<?> updateNotes(@PathVariable String code, @RequestBody Map<String, String> body) {
        try {
            return ResponseEntity.ok(paymentService.updateNotes(code, body.get("transactionRef"), body.get("notes")));
        } catch (RuntimeException e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }

    // DELETE /api/payments/{code} — ADMIN only
    @DeleteMapping("/{code}")
    @PreAuthorize("hasRole('ADMIN')")
    public ResponseEntity<?> delete(@PathVariable String code) {
        try {
            paymentService.delete(code);
            return ResponseEntity.ok(Map.of("message", "Payment deleted"));
        } catch (RuntimeException e) {
            return ResponseEntity.badRequest().body(Map.of("error", e.getMessage()));
        }
    }
}
